name: NPM Package

on:
    push:
        branches:
            - master
        paths:
            - package.json

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup node 12
                uses: actions/setup-node@v2
                with:
                    node-version: 12.x
            -   run: npm ci
            -   run: npm run build
    publish:
        runs-on: ubuntu-latest
        needs:
            - test
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v2
                with:
                    node-version: '12.x'
                    registry-url: 'https://registry.npmjs.org'
            -   run: npm install
            -   run: npm run build
            -   run: npm publish
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
